//! Lens profile lookup in the bundled lensfun database (CC-BY-SA 3.0,
//! https://lensfun.github.io). `data/lensfun.json` is generated by
//! `scripts/lensfun.mjs`. Matching is by camera model (crop factor) and a
//! token score on the lens name from EXIF; calibrations are interpolated
//! over focal length and aperture.

use crate::geometry::LensProfile;
use serde::Deserialize;
use std::sync::OnceLock;

#[derive(Deserialize)]
struct Db {
    cameras: Vec<Camera>,
    lenses: Vec<LensEntry>,
}

#[derive(Deserialize)]
struct Camera {
    maker: String,
    model: String,
    #[serde(default)]
    mount: String,
    crop: f32,
}

#[derive(Deserialize)]
struct LensEntry {
    maker: String,
    model: String,
    #[serde(default)]
    mounts: Vec<String>,
    crop: f32,
    #[serde(default)]
    dist: Vec<Dist>,
    #[serde(default)]
    vig: Vec<Vig>,
    #[serde(default)]
    tca: Vec<Tca>,
}

#[derive(Deserialize)]
struct Dist {
    f: f32,
    m: String,
    p: Vec<f32>,
}

#[derive(Deserialize)]
struct Vig {
    f: f32,
    #[serde(default)]
    ap: Option<f32>,
    #[serde(default)]
    d: Option<f32>,
    k: Vec<f32>,
}

#[derive(Deserialize)]
struct Tca {
    f: f32,
    m: String,
    p: Vec<f32>,
}

static DB: OnceLock<Option<Db>> = OnceLock::new();

fn db() -> Option<&'static Db> {
    DB.get_or_init(|| {
        let text = include_str!("../data/lensfun.json");
        match serde_json::from_str::<Db>(text) {
            Ok(d) => {
                log::info!("lensfun: {} cameras, {} lenses", d.cameras.len(), d.lenses.len());
                Some(d)
            }
            Err(e) => {
                log::warn!("lensfun: cannot parse database: {e}");
                None
            }
        }
    })
    .as_ref()
}

/// Lowercase alphanumeric tokens; "f/3.5-5.6" becomes "f3.5-5.6" etc.
fn tokens(s: &str) -> Vec<String> {
    s.to_ascii_lowercase()
        .replace("f/", "f")
        .split(|c: char| c.is_whitespace() || c == ',' || c == '(' || c == ')' || c == '/')
        .filter(|t| !t.is_empty())
        .map(|t| t.trim_matches(|c: char| !c.is_alphanumeric() && c != '.' && c != '-').to_string())
        .filter(|t| !t.is_empty())
        .collect()
}

fn norm(s: &str) -> String {
    s.chars().filter(|c| c.is_alphanumeric()).collect::<String>().to_ascii_lowercase()
}

/// Similarity of two names in 0..1 (token overlap, with focal-range tokens weighted).
fn score(a: &str, b: &str) -> f32 {
    let ta = tokens(a);
    let tb = tokens(b);
    if ta.is_empty() || tb.is_empty() {
        return 0.0;
    }
    let weight = |t: &str| if t.contains("mm") || t.starts_with('f') && t.chars().nth(1).map_or(false, |c| c.is_ascii_digit()) { 3.0 } else { 1.0 };
    let mut hit = 0.0;
    let mut total = 0.0;
    for t in &ta {
        let w = weight(t);
        total += w;
        if tb.iter().any(|u| u == t) {
            hit += w;
        }
    }
    let mut hit_b = 0.0;
    let mut total_b = 0.0;
    for t in &tb {
        let w = weight(t);
        total_b += w;
        if ta.iter().any(|u| u == t) {
            hit_b += w;
        }
    }
    0.5 * (hit / total + hit_b / total_b)
}

fn camera_crop(db: &Db, camera: &str) -> Option<(f32, String)> {
    let n = norm(camera);
    if n.is_empty() {
        return None;
    }
    // exact normalised match first, then containment
    let exact = db.cameras.iter().find(|c| norm(&c.model) == n || norm(&format!("{} {}", c.maker, c.model)) == n);
    let cam = exact.or_else(|| db.cameras.iter().find(|c| n.contains(&norm(&c.model)) && norm(&c.model).len() >= 6))?;
    Some((cam.crop, cam.mount.clone()))
}

fn lerp(a: f32, b: f32, t: f32) -> f32 {
    a + (b - a) * t
}

/// Interpolate a per-focal list: nearest two entries by focal length.
fn pick2<'a, T>(items: &'a [T], focal: f32, f: impl Fn(&T) -> f32) -> Option<(&'a T, &'a T, f32)> {
    if items.is_empty() {
        return None;
    }
    let mut sorted: Vec<&T> = items.iter().collect();
    sorted.sort_by(|a, b| f(a).partial_cmp(&f(b)).unwrap_or(std::cmp::Ordering::Equal));
    if focal <= f(sorted[0]) {
        return Some((sorted[0], sorted[0], 0.0));
    }
    if focal >= f(sorted[sorted.len() - 1]) {
        let l = sorted[sorted.len() - 1];
        return Some((l, l, 0.0));
    }
    for w in sorted.windows(2) {
        let (a, b) = (w[0], w[1]);
        if focal >= f(a) && focal <= f(b) {
            let t = if f(b) > f(a) { (focal - f(a)) / (f(b) - f(a)) } else { 0.0 };
            return Some((a, b, t));
        }
    }
    None
}

/// Find the calibration for a photo. Returns None when the lens is unknown.
pub fn lookup(camera: Option<&str>, lens: Option<&str>, focal: Option<f32>, aperture: Option<f32>) -> Option<LensProfile> {
    let db = db()?;
    let lens_name = lens?.trim();
    if lens_name.is_empty() {
        return None;
    }
    let (cam_crop, cam_mount) = camera.and_then(|c| camera_crop(db, c)).unwrap_or((0.0, String::new()));
    let mut best: Option<(&LensEntry, f32)> = None;
    for l in &db.lenses {
        let mut s = score(lens_name, &l.model);
        if s <= 0.0 {
            continue;
        }
        if !cam_mount.is_empty() && l.mounts.iter().any(|m| *m == cam_mount) {
            s += 0.1;
        }
        if cam_crop > 0.0 && (l.crop - cam_crop).abs() < 0.05 {
            s += 0.1;
        }
        if best.map_or(true, |(_, bs)| s > bs) {
            best = Some((l, s));
        }
    }
    let (l, s) = best?;
    if s < 0.6 {
        log::info!("lensfun: no confident match for {lens_name:?} (best {:?} at {s:.2})", l.model);
        return None;
    }
    let focal = focal.unwrap_or_else(|| l.dist.first().map(|d| d.f).unwrap_or(50.0));
    let mut p = LensProfile {
        name: l.model.clone(),
        crop_scale: if cam_crop > 0.0 { l.crop / cam_crop } else { 1.0 },
        tca: [1.0, 1.0],
        ..Default::default()
    };
    if let Some((a, b, t)) = pick2(&l.dist, focal, |d| d.f) {
        let model = |m: &str| match m {
            "ptlens" => 1u8,
            "poly5" => 3,
            _ => 2,
        };
        if a.m == b.m {
            p.dist_model = model(&a.m);
            for i in 0..3 {
                p.dist[i] = lerp(*a.p.get(i).unwrap_or(&0.0), *b.p.get(i).unwrap_or(&0.0), t);
            }
        } else {
            let n = if t < 0.5 { a } else { b };
            p.dist_model = model(&n.m);
            for i in 0..3 {
                p.dist[i] = *n.p.get(i).unwrap_or(&0.0);
            }
        }
    }
    if !l.vig.is_empty() {
        // nearest focal, then nearest aperture, preferring far distances
        let mut cands: Vec<&Vig> = l.vig.iter().collect();
        let df = |v: &Vig| (v.f - focal).abs();
        let minf = cands.iter().map(|v| df(v)).fold(f32::MAX, f32::min);
        cands.retain(|v| df(v) <= minf + 0.01);
        if let Some(ap) = aperture {
            let da = |v: &Vig| (v.ap.unwrap_or(ap) - ap).abs();
            let mina = cands.iter().map(|v| da(v)).fold(f32::MAX, f32::min);
            cands.retain(|v| da(v) <= mina + 0.01);
        }
        cands.sort_by(|a, b| b.d.unwrap_or(0.0).partial_cmp(&a.d.unwrap_or(0.0)).unwrap_or(std::cmp::Ordering::Equal));
        if let Some(v) = cands.first() {
            for i in 0..3 {
                p.vig[i] = *v.k.get(i).unwrap_or(&0.0);
            }
        }
    }
    if let Some((a, b, t)) = pick2(&l.tca, focal, |c| c.f) {
        let kr = lerp(*a.p.first().unwrap_or(&1.0), *b.p.first().unwrap_or(&1.0), t);
        let kb = lerp(*a.p.get(1).unwrap_or(&1.0), *b.p.get(1).unwrap_or(&1.0), t);
        if kr > 0.9 && kr < 1.1 && kb > 0.9 && kb < 1.1 {
            p.tca = [kr, kb];
        }
    }
    log::info!(
        "lensfun: {lens_name:?} -> {:?} (score {s:.2}, focal {focal}, model {}, crop_scale {:.3})",
        p.name,
        p.dist_model,
        p.crop_scale
    );
    Some(p)
}
